'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */

    let data = [{
      "userid": 2,
      "reviewid": 49,
      "content": "com.oakley.Y-find"
    }, {
      "userid": 2,
      "reviewid": 32,
      "content": "com.jigsy.Stim"
    }, {
      "userid": 2,
      "reviewid": 50,
      "content": "gov.ca.Cookley"
    }, {
      "userid": 2,
      "reviewid": 46,
      "content": "com.sitemeter.Otcom"
    }, {
      "userid": 2,
      "reviewid": 7,
      "content": "org.archive.Stim"
    }, {
      "userid": 2,
      "reviewid": 9,
      "content": "com.blogs.Domainer"
    }, {
      "userid": 2,
      "reviewid": 6,
      "content": "com.mysql.Fintone"
    }, {
      "userid": 2,
      "reviewid": 35,
      "content": "gov.ca.Sonsing"
    }, {
      "userid": 2,
      "reviewid": 13,
      "content": "uk.co.dailymail.Redhold"
    }, {
      "userid": 1,
      "reviewid": 15,
      "content": "edu.ucsd.Regrant"
    }, {
      "userid": 1,
      "reviewid": 40,
      "content": "net.furl.Ventosanzap"
    }, {
      "userid": 2,
      "reviewid": 18,
      "content": "edu.nyu.Biodex"
    }, {
      "userid": 2,
      "reviewid": 20,
      "content": "au.com.google.Flexidy"
    }, {
      "userid": 2,
      "reviewid": 36,
      "content": "com.theatlantic.Y-find"
    }, {
      "userid": 1,
      "reviewid": 4,
      "content": "com.github.Daltfresh"
    }, {
      "userid": 1,
      "reviewid": 13,
      "content": "com.parallels.Tresom"
    }, {
      "userid": 2,
      "reviewid": 44,
      "content": "com.theglobeandmail.Holdlamis"
    }, {
      "userid": 2,
      "reviewid": 45,
      "content": "la.51.Ventosanzap"
    }, {
      "userid": 2,
      "reviewid": 36,
      "content": "com.printfriendly.Toughjoyfax"
    }, {
      "userid": 2,
      "reviewid": 25,
      "content": "ly.ow.Konklux"
    }, {
      "userid": 1,
      "reviewid": 45,
      "content": "com.vinaora.Stim"
    }, {
      "userid": 1,
      "reviewid": 24,
      "content": "com.ihg.Tres-Zap"
    }, {
      "userid": 2,
      "reviewid": 39,
      "content": "la.51.Viva"
    }, {
      "userid": 2,
      "reviewid": 2,
      "content": "com.sfgate.Fix San"
    }, {
      "userid": 1,
      "reviewid": 31,
      "content": "us.tx.state.Quo Lux"
    }, {
      "userid": 2,
      "reviewid": 12,
      "content": "com.eventbrite.Ventosanzap"
    }, {
      "userid": 1,
      "reviewid": 44,
      "content": "com.goodreads.Prodder"
    }, {
      "userid": 2,
      "reviewid": 21,
      "content": "com.istockphoto.Greenlam"
    }, {
      "userid": 1,
      "reviewid": 38,
      "content": "edu.ucsd.Pannier"
    }, {
      "userid": 1,
      "reviewid": 12,
      "content": "com.artisteer.Zoolab"
    }, {
      "userid": 1,
      "reviewid": 46,
      "content": "com.chronoengine.Opela"
    }, {
      "userid": 1,
      "reviewid": 35,
      "content": "com.vimeo.Kanlam"
    }, {
      "userid": 2,
      "reviewid": 27,
      "content": "edu.arizona.Zathin"
    }, {
      "userid": 1,
      "reviewid": 27,
      "content": "com.photobucket.Tresom"
    }, {
      "userid": 2,
      "reviewid": 35,
      "content": "ch.admin.Bytecard"
    }, {
      "userid": 1,
      "reviewid": 1,
      "content": "org.un.Gembucket"
    }, {
      "userid": 2,
      "reviewid": 49,
      "content": "us.imageshack.Transcof"
    }, {
      "userid": 2,
      "reviewid": 42,
      "content": "com.zimbio.Redhold"
    }, {
      "userid": 1,
      "reviewid": 23,
      "content": "edu.yale.Bytecard"
    }, {
      "userid": 1,
      "reviewid": 42,
      "content": "com.imgur.Lotlux"
    }, {
      "userid": 2,
      "reviewid": 8,
      "content": "jp.or.plala.Quo Lux"
    }, {
      "userid": 1,
      "reviewid": 17,
      "content": "com.wunderground.Quo Lux"
    }, {
      "userid": 1,
      "reviewid": 11,
      "content": "gov.ed.Kanlam"
    }, {
      "userid": 2,
      "reviewid": 45,
      "content": "com.aol.Redhold"
    }, {
      "userid": 1,
      "reviewid": 48,
      "content": "com.jigsy.Zoolab"
    }, {
      "userid": 1,
      "reviewid": 18,
      "content": "com.alibaba.Bitwolf"
    }, {
      "userid": 1,
      "reviewid": 4,
      "content": "com.surveymonkey.Job"
    }, {
      "userid": 1,
      "reviewid": 42,
      "content": "ru.mail.Namfix"
    }, {
      "userid": 2,
      "reviewid": 9,
      "content": "cn.desdev.Regrant"
    }, {
      "userid": 2,
      "reviewid": 1,
      "content": "com.economist.Tresom"
    }, {
      "userid": 1,
      "reviewid": 39,
      "content": "edu.cornell.Y-Solowarm"
    }, {
      "userid": 2,
      "reviewid": 31,
      "content": "com.icq.Aerified"
    }, {
      "userid": 1,
      "reviewid": 19,
      "content": "com.nifty.Kanlam"
    }, {
      "userid": 2,
      "reviewid": 48,
      "content": "edu.yale.Treeflex"
    }, {
      "userid": 1,
      "reviewid": 10,
      "content": "com.skype.Otcom"
    }, {
      "userid": 2,
      "reviewid": 40,
      "content": "com.boston.Pannier"
    }, {
      "userid": 2,
      "reviewid": 33,
      "content": "gov.noaa.It"
    }, {
      "userid": 2,
      "reviewid": 7,
      "content": "com.wikispaces.Sub-Ex"
    }, {
      "userid": 1,
      "reviewid": 44,
      "content": "uk.co.timesonline.Greenlam"
    }, {
      "userid": 2,
      "reviewid": 20,
      "content": "com.hexun.Rank"
    }, {
      "userid": 1,
      "reviewid": 30,
      "content": "gov.epa.Solarbreeze"
    }, {
      "userid": 1,
      "reviewid": 15,
      "content": "com.hugedomains.Duobam"
    }, {
      "userid": 1,
      "reviewid": 20,
      "content": "com.purevolume.Greenlam"
    }, {
      "userid": 1,
      "reviewid": 27,
      "content": "com.smugmug.Lotlux"
    }, {
      "userid": 2,
      "reviewid": 17,
      "content": "net.furl.Aerified"
    }, {
      "userid": 2,
      "reviewid": 33,
      "content": "com.ucoz.Zoolab"
    }, {
      "userid": 2,
      "reviewid": 25,
      "content": "com.mediafire.Trippledex"
    }, {
      "userid": 2,
      "reviewid": 48,
      "content": "edu.cornell.Wrapsafe"
    }, {
      "userid": 2,
      "reviewid": 4,
      "content": "com.wordpress.Bytecard"
    }, {
      "userid": 1,
      "reviewid": 19,
      "content": "com.microsoft.Otcom"
    }, {
      "userid": 2,
      "reviewid": 20,
      "content": "com.yellowbook.Job"
    }, {
      "userid": 1,
      "reviewid": 33,
      "content": "net.slideshare.Tin"
    }, {
      "userid": 2,
      "reviewid": 11,
      "content": "com.prnewswire.Cardguard"
    }, {
      "userid": 1,
      "reviewid": 1,
      "content": "com.time.Y-Solowarm"
    }, {
      "userid": 2,
      "reviewid": 48,
      "content": "com.scribd.Zaam-Dox"
    }, {
      "userid": 2,
      "reviewid": 4,
      "content": "com.ihg.Redhold"
    }, {
      "userid": 1,
      "reviewid": 31,
      "content": "com.shutterfly.Viva"
    }, {
      "userid": 2,
      "reviewid": 33,
      "content": "cn.360.Flexidy"
    }, {
      "userid": 2,
      "reviewid": 21,
      "content": "com.ucoz.Zathin"
    }, {
      "userid": 1,
      "reviewid": 17,
      "content": "com.seattletimes.Fix San"
    }, {
      "userid": 1,
      "reviewid": 46,
      "content": "com.businessinsider.Prodder"
    }, {
      "userid": 1,
      "reviewid": 42,
      "content": "fr.pagesperso-orange.Flexidy"
    }, {
      "userid": 2,
      "reviewid": 35,
      "content": "org.pbs.Veribet"
    }, {
      "userid": 1,
      "reviewid": 44,
      "content": "com.businesswire.Zaam-Dox"
    }, {
      "userid": 2,
      "reviewid": 24,
      "content": "com.ebay.Regrant"
    }, {
      "userid": 1,
      "reviewid": 48,
      "content": "com.bluehost.Otcom"
    }, {
      "userid": 1,
      "reviewid": 43,
      "content": "com.hugedomains.Cookley"
    }, {
      "userid": 2,
      "reviewid": 28,
      "content": "me.about.Wrapsafe"
    }, {
      "userid": 1,
      "reviewid": 13,
      "content": "com.huffingtonpost.Sonsing"
    }, {
      "userid": 2,
      "reviewid": 29,
      "content": "com.hp.Tempsoft"
    }, {
      "userid": 2,
      "reviewid": 47,
      "content": "org.bbb.Otcom"
    }, {
      "userid": 2,
      "reviewid": 45,
      "content": "co.g.Voyatouch"
    }, {
      "userid": 1,
      "reviewid": 13,
      "content": "com.buzzfeed.Tampflex"
    }, {
      "userid": 1,
      "reviewid": 39,
      "content": "com.typepad.Domainer"
    }, {
      "userid": 2,
      "reviewid": 48,
      "content": "com.over-blog.Holdlamis"
    }, {
      "userid": 1,
      "reviewid": 15,
      "content": "com.hc360.Latlux"
    }, {
      "userid": 1,
      "reviewid": 32,
      "content": "com.google.Overhold"
    }, {
      "userid": 1,
      "reviewid": 14,
      "content": "edu.utexas.Daltfresh"
    }, {
      "userid": 1,
      "reviewid": 20,
      "content": "com.photobucket.Andalax"
    }, {
      "userid": 1,
      "reviewid": 43,
      "content": "ru.ucoz.Voltsillam"
    }]

    data.map(item => {
      item.createdAt = Sequelize.literal('NOW()')
      item.updatedAt = Sequelize.literal('NOW()')
      return item
    })
    await queryInterface.bulkInsert('CommentReplies', data, {});

  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
